#
# 这是免费软件，MIT许可使用.
# 
# 版权 (C) 2019 P3TERX <https://p3terx.com>
# 版权 (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
# 

name: 编译x86_64固件
on:
   push:
     branches: 
      - master
   schedule:
     - cron: 0 20 * * *
   release:
     types: [published]

jobs:

  build:

    # 虚拟机系统:ubuntu-latest/Windows-latest/macOS-latest
    runs-on: ubuntu-latest
    
    if: github.event.repository.owner.id == github.event.sender.id

    steps:

      - name: 检测
        # 引用外部Action
        uses: actions/checkout@v2
        with:
          ref: master

      - name: 空间清理
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf swig
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          sudo timedatectl set-timezone "Asia/Shanghai"
          
      # - name: 同步最新的源码
        # run: |
         # git remote add openwrt https://github.com/coolsnowwolf/lede.git
         # git pull openwrt master
         # git remote -v
          
      - name: 自定义插件主题
        run: |
          cd package
          mkdir openwrt-packages
          cd openwrt-packages 
          git clone https://github.com/openwrt-develop/luci-theme-atmaterial.git
          git clone https://github.com/aboutboy/luci-theme-butongwifi.git
          git clone https://github.com/Leo-Jo-My/luci-theme-opentomcat
      - name: 更新feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      - name: 生成配置文件
        run: |
         curl -fsSL https://raw.githubusercontent.com/yangchlin/lede/master/openwrt/x86_64.config >.config
         bash <(curl -fsSL https://raw.githubusercontent.com/yangchlin/lede/master/openwrt/diy86_64.sh)
         ./scripts/feeds install -a
          make defconfig
      - name: DL下载
        run: |
          make download -j8
          find ./dl/ -size -1024c -exec rm -f {} \;
          df -h
      - name: 编译固件
        run: |
          make -j$(nproc) || make -j1 V=s
          echo "======================="
          echo "空间使用:"
          echo "======================="
          df -h
          echo "======================="
          du -h --max-depth=1 ./ --exclude=build_dir --exclude=bin
          du -h --max-depth=1 ./build_dir
          du -h --max-depth=1 ./bin
      - name: 准备artifact
        run: |
          mkdir -p ./new/firmware
          mkdir -p ./new/package
          cp -rf $(find ./bin/packages/ -type f -name "*.ipk") ./new/package
          find bin/targets/ -name "*combined*img*" | xargs -i mv -f {} ./new/firmware
          cd ./new/firmware
          gzip *.img

      - name: 上传 Firmware
        uses: actions/upload-artifact@v2
        with:
          name: x86_64_LEDE firmware
          path: ./new/firmware
      - name: 上传 IPK
        uses: actions/upload-artifact@v2
        with:
          name: x86_64_LEDE-Ipk
          path: ./new/package
