#
# 这是免费软件，MIT许可使用.
# 
# 版权 (C) 2019 P3TERX <https://p3terx.com>
# 版权 (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
# 

name: 编译x86_64固件
on:
  # push:
    # branches: 
     # - master
  # schedule:
  #   - cron: 0 20 * * *
  # release:
  #   types: [published]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: 检测
        uses: actions/checkout@master
        with:
          ref: master

      - name: 空间清理
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          
          # 利用挂载在 /mnt/ 的 14G 额外空间:
          # sudo mkdir -p -m 777 /mnt/openwrt/bin /mnt/openwrt/build_dir/host /mnt/openwrt/build_dir/hostpkg /mnt/openwrt/dl /mnt/openwrt/feeds /mnt/openwrt/staging_dir
          # ln -s /mnt/openwrt/bin ./bin
          # mkdir -p ./build_dir/host && ln -s /mnt/openwrt/build_dir/host ./build_dir/host
          # mkdir -p ./build_dir/host && ln -s /mnt/openwrt/build_dir/hostpkg ./build_dir/hostpkg
          # ln -s /mnt/openwrt/dl ./dl
          # ln -s /mnt/openwrt/feeds ./feeds
          # ln -s /mnt/openwrt/staging_dir ./staging_dir
          
          df -h
          
      - name: 自定义插件主题
        run: |
          cd package
          mkdir openwrt-packages
          cd openwrt-packages 
          git clone https://github.com/openwrt-develop/luci-theme-atmaterial.git
          git clone https://github.com/aboutboy/luci-theme-butongwifi.git
          git clone https://github.com/tvheadend/tvheadend.git
      - name: 更新feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      - name: 生成配置文件
        run: |
         curl -fsSL https://raw.githubusercontent.com/yangchlin/lede/master/openwrt/x86_64.config >.config
         bash <(curl -fsSL https://raw.githubusercontent.com/yangchlin/lede/master/openwrt/diy86_64.sh)
         ./scripts/feeds install -a
          make defconfig
      - name: 进行下载
        run: |
          make download -j8
          find ./dl/ -size -1024c -exec rm -f {} \;
          df -h
      - name: 编译固件
        run: |
          make -j$(nproc) || make -j1 V=s
          echo "======================="
          echo "空间使用:"
          echo "======================="
          df -h
          echo "======================="
          du -h --max-depth=1 ./ --exclude=build_dir --exclude=bin
          du -h --max-depth=1 ./build_dir
          du -h --max-depth=1 ./bin
      - name: 准备artifact
        run: find ./bin/targets/ -type d -name "packages" | xargs rm -rf {}

      - name: 上传artifact
        uses: actions/upload-artifact@master
        with:
          name: x86_64_LEDE firmware
          path: ./bin/targets/